### PR TITLE
updated to get values in HostBuilder

### PR DESCRIPTION
**Pull request by RoLYroLLs**

### CODE REVIEW

**Comment by marcsstevenson** [comment]
@RoLYroLLs - you're wanting to use the options pattern, I see. This can be a real pain to get working. I'll dig into that PR if I get time later but in the interim just wanting to make sure that you have found this: [Docs here](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-8.0).

**Comment by RoLYroLLs** [comment]
> @RoLYroLLs - you're wanting to use the options pattern, I see. This can be a real pain to get working. I'll dig into that PR if I get time later but in the interim just wanting to make sure that you have found this: [Docs here](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-8.0).

Yes I have. Thanks! That's what I found for doing options pattern on our Web API.

Take your time, my function currently works fine using this method. However, I'm still curious, I do want to learn better/proper/alternative ways of doing this, of course until it becomes irrelevant with .Net 9/10/etc. lol. ;)

Thanks!

**Comment by marcsstevenson** [comment]
@RoLYroLLs - commit 2 on this PR should be what you're after am I right? This also works with User Secrets.

**Comment by RoLYroLLs** [comment]
@marcsstevenson YES! This works as expected and even better since now I have those settings for DI. I could have easily figured this out, Guess I just got into my own head thinking "this is a function so it's a bit different" lol

**Comment by marcsstevenson** [comment]
MS need to hurry up and make a love child between Web APIs and Function Apps. They're 90% the same now anyway.

**Pull request merged**
